services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: workpal
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  dev:
    build:
      context: ../..
    env_file:
      - .env
    command: npm run dev
    entrypoint: ./infra/docker/entrypoint.sh
    volumes:
      - ../../:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://root:root@mysql:3306/workpal
    depends_on:
      - mysql

volumes:
  mysql_data:
